from PyQt5 import QtCore, QtGui, QtWidgets
import process01 as p

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 70, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listaKernels = QtWidgets.QListWidget(self.centralwidget)
        self.listaKernels.setEnabled(True)
        self.listaKernels.setGeometry(QtCore.QRect(50, 200, 251, 341))
        self.listaKernels.setAutoFillBackground(False)
        self.listaKernels.setObjectName("listaKernels")
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaKernels.addItem(item)
        self.limiarBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.limiarBox.setGeometry(QtCore.QRect(170, 70, 71, 22))
        self.limiarBox.setDecimals(2)
        self.limiarBox.setMaximum(254.99)
        self.limiarBox.setProperty("value", 100.0)
        self.limiarBox.setObjectName("limiarBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.blurButton = QtWidgets.QRadioButton(self.centralwidget)
        self.blurButton.setGeometry(QtCore.QRect(50, 30, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.blurButton.setFont(font)
        self.blurButton.setObjectName("blurButton")
        self.verFrame = QtWidgets.QPushButton(self.centralwidget)
        self.verFrame.setGeometry(QtCore.QRect(430, 60, 111, 41))
        self.verFrame.setObjectName("verFrame")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(360, 200, 241, 341))
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 160, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.limiarBox.valueChanged.connect(self.atualizar)
        self.blurButton.toggled.connect(self.atualizar)
        self.listaKernels.clicked.connect(self.atualizar)
        self.verFrame.clicked.connect(self.atualizar)

    def atualizar(self):
        self.textEdit.append("Iniciar")
        nucleo = self.listaKernels.currentItem()
        limiar = self.limiarBox.value()
        self.textEdit.append("nucleo: "+nucleo.text())
        self.textEdit.append("limiar: "+str(limiar))

        p.liberar()
        p.webcam(self.blurButton.isChecked(), nucleo.text(), limiar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Limiar:"))
        __sortingEnabled = self.listaKernels.isSortingEnabled()
        self.listaKernels.setSortingEnabled(False)
        item = self.listaKernels.item(0)
        item.setText(_translate("MainWindow", "identity"))
        item = self.listaKernels.item(1)
        item.setText(_translate("MainWindow", "edge detection"))
        item = self.listaKernels.item(2)
        item.setText(_translate("MainWindow", "laplacian"))
        item = self.listaKernels.item(3)
        item.setText(_translate("MainWindow", "laplacian w/ diagonals"))
        item = self.listaKernels.item(4)
        item.setText(_translate("MainWindow", "laplacian of gaussian"))
        item = self.listaKernels.item(5)
        item.setText(_translate("MainWindow", "scharr"))
        item = self.listaKernels.item(6)
        item.setText(_translate("MainWindow", "sobel edge horizontal"))
        item = self.listaKernels.item(7)
        item.setText(_translate("MainWindow", "sobel edge vertical"))
        item = self.listaKernels.item(8)
        item.setText(_translate("MainWindow", "line detection 45°"))
        item = self.listaKernels.item(9)
        item.setText(_translate("MainWindow", "line detection 135°"))
        item = self.listaKernels.item(10)
        item.setText(_translate("MainWindow", "box blur"))
        item = self.listaKernels.item(11)
        item.setText(_translate("MainWindow", "gaussian blur 3x3"))
        item = self.listaKernels.item(12)
        item.setText(_translate("MainWindow", "gaussian blur 5x5"))
        item = self.listaKernels.item(13)
        item.setText(_translate("MainWindow", "sharpen"))
        item = self.listaKernels.item(14)
        item.setText(_translate("MainWindow", "unsharp masking"))
        self.listaKernels.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Escolha um kernel:"))
        self.blurButton.setText(_translate("MainWindow", "Detecção de Blur Automática"))
        self.verFrame.setText(_translate("MainWindow", "Atualizar"))
        self.label_4.setText(_translate("MainWindow", "Logs:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    p.liberar()
    sys.exit(app.exec_())
